# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Reason Creative
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Web and Graphic Design in Brooklyn, NY. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.reasoncreative.com" # the base hostname & protocol for your site
excludes: ["package.json"]

collections:
  portfolio_items:
    output: true
    permalink: /portfolio/:path/

# Build settings
markdown: kramdown